import { put } from '@vercel/blob';
import { requirePostforgeAccess } from '../../lib/access';
import { jsonResponse } from '../../lib/validation';

export const maxDuration = 300;

function clean(value, max = 220) {
  return String(value || '').replace(/[{}]/g, '').replace(/\s+/g, ' ').trim().slice(0, max);
}

function reelScenePrompt({ segment, index, pillarId }) {
  const palette = {
    news: 'black editorial newsroom, white type zones, blue and red signal lights',
    tool: 'premium SaaS product lab, cobalt screens, cyan UI, clean creator desk',
    income: 'dark creator business dashboard, emerald finance signals, warm gold highlights',
    transformation: 'cinematic before-after work scene, violet and amber mood, identity-shift energy',
    automation: 'workflow command center, teal routing lines, orange automation sparks'
  }[pillarId] || 'dark premium AI creator studio, neon accents, cinematic lighting';

  return `Create a vertical faceless Reel background image, 1024x1536.
Style: cinematic AI creator B-roll, premium Instagram reel, realistic depth, sharp lighting, no person looking into camera, no text, no letters, no numbers, no captions, no labels, no logos, no UI words.
Palette: ${palette}.
Scene ${index + 1} beat: ${clean(segment.beat, 80)}.
Visual direction: ${clean(segment.visual, 260)}.
Voiceover meaning to support: ${clean(segment.voiceover, 260)}.
On-screen text will be added later by the app, so leave clean negative space in the lower third only.
Strict rules: the image itself must contain zero readable text of any kind, no random words, no fake logos, no watermark, no distorted hands, no face close-up, no clutter over the lower-third text space, make it feel like a viral AI productivity/research reel frame.`;
}

async function generateImage(apiKey, prompt) {
  const res = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({ model: 'gpt-image-1', prompt, size: '1024x1536', quality: 'medium', n: 1 })
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Image API failed ${res.status}: ${err.slice(0, 220)}`);
  }

  const data = await res.json();
  const b64 = data.data?.[0]?.b64_json;
  if (!b64) throw new Error('Image API returned no reel scene.');
  return `data:image/png;base64,${b64}`;
}

async function uploadImage(dataUrl, index) {
  if (!process.env.BLOB_READ_WRITE_TOKEN) return null;

  const base64 = dataUrl.replace(/^data:image\/png;base64,/, '');
  const buffer = Buffer.from(base64, 'base64');
  const blob = await put(`postforge/reels/${Date.now()}-${index}.png`, buffer, {
    access: 'public',
    contentType: 'image/png'
  });

  return blob.url;
}

export async function POST(request) {
  try {
    const blocked = requirePostforgeAccess(request);
    if (blocked) return blocked;

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) return jsonResponse({ error: 'OPENAI_API_KEY is not configured.' }, 500);

    const { output, pillarId = 'news' } = await request.json();
    const segments = output?.script_segments;
    if (!Array.isArray(segments) || !segments.length) {
      return jsonResponse({ error: 'A generated Reel Script with script_segments is required.' }, 400);
    }

    const sceneSegments = segments.slice(0, 7);
    const assets = [];

    for (let i = 0; i < sceneSegments.length; i += 1) {
      const segment = sceneSegments[i];
      try {
        const prompt = reelScenePrompt({ segment, index: i, pillarId });
        const image = await generateImage(apiKey, prompt);
        let imageUrl = null;
        let uploadError = null;

        try {
          imageUrl = await uploadImage(image, i);
        } catch (error) {
          uploadError = error.message;
        }

        assets.push({
          index: i,
          label: `${segment.timestamp || `Scene ${i + 1}`} / ${segment.beat || 'beat'}`,
          image,
          imageUrl,
          uploadError,
          on_screen_text: segment.on_screen_text || '',
          voiceover: segment.voiceover || '',
          edit_note: segment.edit_note || '',
          timestamp: segment.timestamp || '',
          success: true
        });
      } catch (error) {
        assets.push({
          index: i,
          label: `${segment.timestamp || `Scene ${i + 1}`} / ${segment.beat || 'beat'}`,
          error: error.message,
          success: false
        });
      }
    }

    return jsonResponse({
      assets,
      successCount: assets.filter(asset => asset.success).length,
      totalCount: assets.length,
      publicUrlCount: assets.filter(asset => asset.imageUrl).length,
      renderMode: 'browser-webm',
      note: 'Scenes are generated by OpenAI. The browser render overlays exact script text and exports a vertical WebM preview.'
    });
  } catch (error) {
    return jsonResponse({ error: error.message }, 500);
  }
}
